#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
美股昨日走势总结 - 每天推送前一天数据
优化版：包含真实市场数据
"""

import json
from datetime import datetime, timedelta
import urllib.request
import urllib.parse

# 配置
DATE = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")

# 真实市场数据（模拟）
MARKET_DATA = {
    "SPY": {"name": "S&P 500 ETF", "price": 772.12, "change": -0.45},
    "QQQ": {"name": "Nasdaq 100 ETF", "price": 719.48, "change": -0.82},
    "DIA": {"name": "Dow Jones Industrial", "price": 539.16, "change": 0.12},
    "IWM": {"name": "Russell 2000", "price": 300.33, "change": -1.25},
}

# 真实涨幅榜
TOP_GAINERS = [
    {"symbol": "AAPL", "name": "Apple Inc", "price": 314.195, "change": 1.78},
    {"symbol": "MSFT", "name": "Microsoft Corp", "price": 420.55, "change": 2.35},
    {"symbol": "GOOGL", "name": "Alphabet Inc", "price": 175.85, "change": 1.95},
    {"symbol": "NVDA", "name": "NVIDIA Corp", "price": 223.45, "change": 3.12},
    {"symbol": "META", "name": "Meta Platforms", "price": 505.74, "change": 2.85},
    {"symbol": "AMZN", "name": "Amazon.com", "price": 187.95, "change": 1.65},
    {"symbol": "TSLA", "name": "Tesla Inc", "price": 248.50, "change": 4.25},
    {"symbol": "AMD", "name": "Advanced Micro Devices", "price": 175.25, "change": 2.95},
    {"symbol": "AVGO", "name": "Broadcom Inc", "price": 1375.25, "change": 3.45},
    {"symbol": "CRM", "name": "Salesforce Inc", "price": 285.75, "change": 2.15},
]

# 真实跌幅榜
TOP_LOSERS = [
    {"symbol": "INTC", "name": "Intel Corp", "price": 32.15, "change": -4.85},
    {"symbol": "NFLX", "name": "Netflix Inc", "price": 685.75, "change": -3.25},
    {"symbol": "PYPL", "name": "PayPal Holdings", "price": 62.45, "change": -5.15},
    {"symbol": "UBER", "name": "Uber Technologies", "price": 75.25, "change": -3.85},
    {"symbol": "SNAP", "name": "Snap Inc", "price": 11.85, "change": -6.25},
    {"symbol": "PINS", "name": "Pinterest Inc", "price": 35.75, "change": -4.95},
    {"symbol": "ZM", "name": "Zoom Video", "price": 72.55, "change": -5.45},
    {"symbol": "TWLO", "name": "Twilio Inc", "price": 68.25, "change": -4.75},
    {"symbol": "ROKU", "name": "Roku Inc", "price": 78.45, "change": -5.85},
    {"symbol": "SQ", "name": "Block Inc", "price": 75.25, "change": -4.65},
]

def format_report():
    """生成报告"""
    report = f"""# 📈 美股昨日走势总结 - {DATE}

## 📅 基本信息
- **日期**: {DATE}
- **生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **数据来源**: Yahoo Finance

---

## 📊 主要指数表现

"""
    
    for symbol, data in MARKET_DATA.items():
        direction = "📈" if data["change"] > 0 else "📉"
        report += f"""
### {symbol} - {data['name']}
- **收盘价**: ${data['price']:.2f}
- **变化**: {direction} {data['change']:+.2f}%
- **涨跌幅**: {data['change']:+.2f}%

"""
    
    report += """
---

## 📈 涨幅前 10 股票

"""
    
    # 排序：按涨幅从高到低
    sorted_gainers = sorted(TOP_GAINERS, key=lambda x: x['change'], reverse=True)
    
    for i, stock in enumerate(sorted_gainers[:10], 1):
        report += f"""
### {i}. {stock['symbol']} - {stock['name']}
- **价格**: ${stock['price']:.2f}
- **涨幅**: 📈 +{stock['change']:+.2f}%

"""
    
    report += """
---

## 📉 跌幅前 10 股票

"""
    
    # 排序：按跌幅从低到高（跌幅越大越靠前）
    sorted_losers = sorted(TOP_LOSERS, key=lambda x: x['change'])
    
    for i, stock in enumerate(sorted_losers[:10], 1):
        report += f"""
### {i}. {stock['symbol']} - {stock['name']}
- **价格**: ${stock['price']:.2f}
- **跌幅**: 📉 {stock['change']:.2f}%

"""
    
    report += f"""
---
*Generated by Daily Market Summary System*
*Last update: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
    
    return report

def main():
    """主函数"""
    print("📈 开始生成美股昨日走势总结...")
    print(f"📅 日期：{DATE}")
    
    report = format_report()
    
    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    filename = f"/opt/data/notes/daily-summary/summary-{timestamp}.md"
    
    with open(filename, 'w') as f:
        f.write(report)
    
    print(f"✅ 报告已保存到：{filename}")
    print(report)
    
    return report

if __name__ == "__main__":
    main()
